SET IDENTITY_INSERT [dbo].[Locations] ON
INSERT INTO [dbo].[Locations] ([Id], [LocationName], [LocationDescription], [TypeLocationId], [CityId], [PhotoLocationId]) VALUES (1, N'Местонахождение неизвестно', N' ', NULL, 1, NULL)
INSERT INTO [dbo].[Locations] ([Id], [LocationName], [LocationDescription], [TypeLocationId], [CityId], [PhotoLocationId]) VALUES (2, N'Музей Лувра', N'один из крупнейших и самый популярный художественный музей мира. Музей расположен в центре Парижа, на правом берегу Сены, на улице Риволи, в 1-м округе столицы.', NULL, 5, NULL)
INSERT INTO [dbo].[Locations] ([Id], [LocationName], [LocationDescription], [TypeLocationId], [CityId], [PhotoLocationId]) VALUES (3, N'Королевская галерея Маурицхёйс', N'Государственная коллекция из 841 работы таких деятелей искусства, как Рембрандт, Вермеер и Гольбейн-младший.', NULL, 2, NULL)
INSERT INTO [dbo].[Locations] ([Id], [LocationName], [LocationDescription], [TypeLocationId], [CityId], [PhotoLocationId]) VALUES (4, N'Театр "Опера-комик"', N'«Опера́-Коми́к»(фр. Opéra-Comique; полное название Национальный театр комической оперы, фр. Théâtre national de l’Opéra-Comique) — оперный театр в Париже, основанный в 1715 году и первоначально предназначенный для постановки комических опер.

Наибольшее значение театр имел в XIX веке, когда он стал одним из центров национальной культуры[2][3]. В этот период в театре прошли мировые премьеры многих известных опер, в том числе «Кармен» Бизе.', NULL, 6, NULL)
INSERT INTO [dbo].[Locations] ([Id], [LocationName], [LocationDescription], [TypeLocationId], [CityId], [PhotoLocationId]) VALUES (5, N'Venice Art Biennale', N'Венецианская биеннале — один из самых известных форумов мирового искусства, международная художественная выставка, проводящаяся раз в два года с участием международного жюри.', NULL, NULL, NULL)
INSERT INTO [dbo].[Locations] ([Id], [LocationName], [LocationDescription], [TypeLocationId], [CityId], [PhotoLocationId]) VALUES (6, N'Мариинский театр', N'Государственный академический Мариинский театр (в 1935—1992 годах — Ленинградский ордена Ленина и ордена Октябрьской Революции академический театр оперы и балета имени С. М. Кирова) — театр оперы и балета в Санкт-Петербурге, один из ведущих музыкальных театров России и мира.

Труппа, основанная ещё в XVIII веке, до революции функционировала под руководством дирекции Императорских театров. В 1784—1886 годах для балетных и оперных спектаклей использовалось преимущественно здание Большого театра (в 1896 году перестроено архитектором В. В. Николя для размещения Санкт-Петербургской консерватории), в 1859—1860 году там же, на Театральной площади, архитектором А. К. Кавосом было выстроено нынешнее здание театра, названное в честь императрицы Марии Александровны.', NULL, NULL, NULL)
INSERT INTO [dbo].[Locations] ([Id], [LocationName], [LocationDescription], [TypeLocationId], [CityId], [PhotoLocationId]) VALUES (7, N'Замок Милотице', N'Замок в стиле барокко в Милотице (район Годонин Южноморавского края), Чехия.', NULL, NULL, NULL)
INSERT INTO [dbo].[Locations] ([Id], [LocationName], [LocationDescription], [TypeLocationId], [CityId], [PhotoLocationId]) VALUES (8, N'Национальном Музее Африканской Культуры', N'В Вашингтоне открылся Национальный музей афроамериканской истории и культуры. Архитектурный дизайн музея был разработан Дэвидом Аджайе, автором московской Школы управления "Сколково".', NULL, NULL, NULL)
SET IDENTITY_INSERT [dbo].[Locations] OFF
